### PR TITLE
v1.1.10

### PR DESCRIPTION
**Pull request by efjacobson**
* __Add Schemas:__
  * `triniti:ovp:event:transcoding-completed`
  * `triniti:ovp:event:transcoding-started`
  * `triniti:ovp:event:transcription-completed`
  * `triniti:ovp:event:transcription-started`

### CODE REVIEW

**Comment by efjacobson** [comment]
@gdbrown couple things: 
- i dont love the field name of `blah_job_identifier`, would rather have something more explicit like `id` or `arn` but `arn` is aws-specific and `id` is confusing because mediaconvert jobs have an id but that is not enough to know what region it happened in
- undecided on whether to include thumbnail/caption events. they could be implicit and derived from the mezzanine. they could also be considered a part of the transcode/transcribe process

**Comment by gdbrown** [comment]
@efjacobson let's make these mixins (in case we need to customize them at the site level)

**Comment by efjacobson** [comment]
@gdbrown converted to mixins

**Comment by efjacobson** [comment]
merged into https://github.com/triniti/schemas/pull/84

**Pull request closed without merging**
