### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by meghedi**
* __Modify Schemas:__
  * `triniti:canvas:mixin:tiktok-embed-block` patch revision `1-0-1`
    * Add `user_name` string field.

### CODE REVIEW

**Comment by gdbrown** [comment]
@meghedi new fields cannot be made required, it breaks all existing schemas.  curious though, why is this even needed?  embeds work without username (just data-video-id attribute is needed).  It would be preferable to not require this if it's not needed for embeds to work.  let me know what scenario this is for.

**Comment by meghedi** [comment]
@gdbrown this what I am trying to implement, the component needs username, since it should be there to work, I think it needs to be required.
https://developer.apple.com/documentation/apple_news/tiktok
let me know what you think.

**Comment by gdbrown** [comment]
@meghedi lol, apple news, well that's putrid.  makes sense but you still can't make it required since that is a breaking schema change.  also, this is a patch level update (on the composer/package.json).  also, how confident are you in that regex for tiktok usernames?

**Comment by meghedi** [comment]
@gdbrown about regex, this is a helpful link, 
https://support.tiktok.com/en/getting-started/setting-up-your-profile/changing-your-username

**Comment by gdbrown** [comment]
@meghedi so the regex pattern needs to be updated to allow periods as well then.

**Comment by meghedi** [comment]
> @meghedi so the regex pattern needs to be updated to allow periods as well then.

@gdbrown  sure, and thanks

**Pull request closed without merging**
