### PR TITLE
v1.1.12

### PR DESCRIPTION
**Pull request by arunkarnati**
* Use `gdbots/schemas` v1.6.6.

### CODE REVIEW

**Comment by gdbrown** [comment]
@arunkarnati not really required.  site/app level schemas apply the final constraint, triniti is just caret

**Comment by arunkarnati** [comment]
> @arunkarnati not really required. site/app level schemas apply the final constraint, triniti is just caret

yes, it works when there is only one root package.json file for the whole project, and `npm install` is run once. But for cms-js, we run the vendor schemas separately with --no-save which installs the latest version of gdbots-schemas and creates multiple versions.

**Comment by gdbrown** [comment]
@arunkarnati indeed, the putrocity of npm and nested dependencies.  use npm dedupe.  i really wish the dependencies were always flat, insanity.

**Comment by arunkarnati** [comment]
Since dependencies can be managed at the actual project level and we don't need to update a dependency's dependency, closing this out.

**Pull request closed without merging**
